== Matrix Instruction Listing

.Configuration Instructions
[cols="3,3,3,2,2,2,3"]
|===
.4+^.^| *Format*    4+^| 63        43                                   ^| 42    39 ^| 38    32
                    4+^| *imm[31:11]*                                   ^| *funct4* ^| *opcode*
                      ^| 31    26 ^| 25       20  ^| 19  15 ^| 14    12 ^| 11     7 ^| 6     0
                      ^| *funct6* ^| *imm[10:5]*  ^|  *rs1* ^| *funct3* ^|   *rd*   ^| *suffix*
.2+^.^| msettype    4+^| 0...00                                         ^|   0000   ^| xxyyy11
                      ^| 000000   ^| 000000       ^|   rs1  ^|   000    ^|    rd    ^| 0111111
.2+^.^| msettypei   4+^| mtypei[31:11]                                  ^|   0000   ^| xxyyy11
                      ^| 000001 2+^| mtypei[10:0]           ^|   000    ^|    rd    ^| 0111111
.2+^.^| msetsew     4+^| 0...00                                         ^|   0000   ^| xxyyy11
                      ^| 000011 2+^| setval                 ^|   000    ^|    rd    ^| 0111111
.2+^.^| msetint     4+^| 0...00                                         ^|   mtf    ^| xxyyy11
                      ^| 000011 2+^| 1                      ^|   000    ^|    rd    ^| 0111111
.2+^.^| munsetint   4+^| 0...00                                         ^|   mtf    ^| xxyyy11
                      ^| 000011 2+^| 0                      ^|   000    ^|    rd    ^| 0111111
.2+^.^| msetfp      4+^| 0...00                                         ^|   mtf    ^| xxyyy11
                      ^| 000011 2+^| setval                 ^|   000    ^|    rd    ^| 0111111
.2+^.^| munsetfp    4+^| 0...00                                         ^|   mtf    ^| xxyyy11
                      ^| 000011 2+^| 0                      ^|   000    ^|    rd    ^| 0111111
.2+^.^| msetba      4+^| 0...00                                         ^|   1010   ^| xxyyy11
                      ^| 000011 2+^| setval                 ^|   000    ^|    rd    ^| 0111111

.2+^.^| msettilem   4+^| 0...00                                         ^|   0000   ^| xxyyy11
                      ^| 000100   ^| 000000        ^|  rs1  ^|   000    ^|    rd    ^| 0111111
.2+^.^| msettilemi  4+^| mtypei[31:11]                                  ^|   0000   ^| xxyyy11
                      ^| 000101 2+^| mtypei[10:0]           ^|   000    ^|    rd    ^| 0111111
.2+^.^| msettilen   4+^| 0...00                                         ^|   0000   ^| xxyyy11
                      ^| 001000   ^| 000000        ^|  rs1  ^|   000    ^|    rd    ^| 0111111
.2+^.^| msettileni  4+^| mtypei[31:11]                                  ^|   0000   ^| xxyyy11
                      ^| 001001 2+^| mtypei[10:0]           ^|   000    ^|    rd    ^| 0111111
.2+^.^| msettilen   4+^| 0...00                                         ^|   0000   ^| xxyyy11
                      ^| 001100   ^| 000000        ^|  rs1  ^|   000    ^|    rd    ^| 0111111
.2+^.^| msettileni  4+^| mtypei[31:11]                                  ^|   0000   ^| xxyyy11
                      ^| 001101 2+^| mtypei[10:0]           ^|   000    ^|    rd    ^| 0111111
.2+^.^| msetpairn   4+^| 0...00                                         ^|   0000   ^| xxyyy11
                      ^| 001110   ^| 000000        ^|  rs1  ^|   000    ^|    rd    ^| 0111111
.2+^.^| msetpairni  4+^| mtypei[31:11]                                  ^|   0000   ^| xxyyy11
                      ^| 001111 2+^| mtypei[10:0]           ^|   000    ^|    rd    ^| 0111111

.2+^.^| msetoutsh   4+^| 0...00                                         ^|   0000   ^| xxyyy11
                      ^| 010000   ^| 000000        ^|  rs1  ^|   000    ^|    rd    ^| 0111111
.2+^.^| msetinsh    4+^| 0...00                                         ^|   0000   ^| xxyyy11
                      ^| 010100   ^| 000000        ^|  rs1  ^|   000    ^|    rd    ^| 0111111
.2+^.^| msetsk      4+^| 0...00                                         ^|   0000   ^| xxyyy11
                      ^| 011000   ^| 000000        ^|  rs1  ^|   000    ^|    rd    ^| 0111111
.2+^.^| msetpadval  4+^| 0...00                                         ^|   0000   ^| xxyyy11
                      ^| 011100   ^| 000000        ^|  rs1  ^|   000    ^|    rd    ^| 0111111
|===

.Load/Store Instructions
[cols="5,3,2,3,3,3,4,5"]
|===
.4+^.^| *Format*    2+^| 63           51  ^| 50 49 ^| 48 47 ^| 46    44 ^| 43    39 ^| 38   32
                    2+^| *resv*           ^|  *mt* ^| *bma* ^|   *eew*  ^| *funct5* ^| *opcode*
                      ^| 31    26 ^|  25  ^| 24 20 ^| 19 15 ^| 14    12 ^| 11     7 ^| 6     0
                      ^| *funct6* ^| *ls* ^| *rs2* ^| *rs1* ^| *funct3* ^| *ms3/md* ^| *suffix*
.2+^.^| mlae*.m     2+^| 0.000            ^|  01   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00000    ^|  0   ^|  rs2  ^|  rs1  ^|    001   ^|     md   ^| 0111111
.2+^.^| mlbe*.m     2+^| 0.000            ^|  10   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00000    ^|  0   ^|  rs2  ^|  rs1  ^|    001   ^|     md   ^| 0111111
.2+^.^| mlce*.m     2+^| 0.000            ^|  00   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00000    ^|  0   ^|  rs2  ^|  rs1  ^|    001   ^|     md   ^| 0111111
.2+^.^| mlre*.m     2+^| 0.000            ^|  11   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00000    ^|  0   ^|  rs2  ^|  rs1  ^|    001   ^|     md   ^| 0111111
.2+^.^| mlate*.m    2+^| 0.000            ^|  01   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00001    ^|  0   ^|  rs2  ^|  rs1  ^|    001   ^|     md   ^| 0111111
.2+^.^| mlbte*.m    2+^| 0.000            ^|  10   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00001    ^|  0   ^|  rs2  ^|  rs1  ^|    001   ^|     md   ^| 0111111
.2+^.^| mlpbte*.m   2+^| 0.001            ^|  10   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00001    ^|  0   ^|  rs2  ^|  rs1  ^|    001   ^|     md   ^| 0111111
.2+^.^| mlcte*.m    2+^| 0.000            ^|  00   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00001    ^|  0   ^|  rs2  ^|  rs1  ^|    001   ^|     md   ^| 0111111
.2+^.^| mlpcte*.m   2+^| 0.001            ^|  00   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00001    ^|  0   ^|  rs2  ^|  rs1  ^|    001   ^|     md   ^| 0111111
.2+^.^| mlrte*.m    2+^| 0.000            ^|  11   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00001    ^|  0   ^|  rs2  ^|  rs1  ^|    001   ^|     md   ^| 0111111

.2+^.^| msae*.m     2+^| 0.000            ^|  01   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00000    ^|  1   ^|  rs2  ^|  rs1  ^|    001   ^|    ms3   ^| 0111111
.2+^.^| msbe*.m     2+^| 0.000            ^|  10   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00000    ^|  1   ^|  rs2  ^|  rs1  ^|    001   ^|    ms3   ^| 0111111
.2+^.^| mspbe*.m    2+^| 0.001            ^|  10   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00000    ^|  1   ^|  rs2  ^|  rs1  ^|    001   ^|    ms3   ^| 0111111
.2+^.^| msce*.m     2+^| 0.000            ^|  00   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00000    ^|  1   ^|  rs2  ^|  rs1  ^|    001   ^|    ms3   ^| 0111111
.2+^.^| mspce*.m    2+^| 0.001            ^|  00   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00000    ^|  1   ^|  rs2  ^|  rs1  ^|    001   ^|    ms3   ^| 0111111
.2+^.^| msre*.m     2+^| 0.000            ^|  11   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00000    ^|  1   ^|  rs2  ^|  rs1  ^|    001   ^|    ms3   ^| 0111111
.2+^.^| msate*.m    2+^| 0.000            ^|  01   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00001    ^|  1   ^|  rs2  ^|  rs1  ^|    001   ^|    ms3   ^| 0111111
.2+^.^| msbte*.m    2+^| 0.000            ^|  10   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00001    ^|  1   ^|  rs2  ^|  rs1  ^|    001   ^|    ms3   ^| 0111111
.2+^.^| mscte*.m    2+^| 0.000            ^|  00   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00001    ^|  1   ^|  rs2  ^|  rs1  ^|    001   ^|    ms3   ^| 0111111
.2+^.^| msrte*.m    2+^| 0.000            ^|  11   ^|  bma  ^|    eew   ^|   00000  ^| xxyyy11
                      ^| 00001    ^|  1   ^|  rs2  ^|  rs1  ^|    001   ^|    ms3   ^| 0111111

.2+^.^| mlae*.v     2+^| 0.000            ^|  01   ^|  bma  ^|    eew   ^|   00001  ^| xxyyy11
                      ^| 00000    ^|  0   ^|  rs2  ^|  rs1  ^|    001   ^|     md   ^| 0111111
.2+^.^| mlbe*.v     2+^| 0.000            ^|  10   ^|  bma  ^|    eew   ^|   00001  ^| xxyyy11
                      ^| 00000    ^|  0   ^|  rs2  ^|  rs1  ^|    001   ^|     md   ^| 0111111
.2+^.^| mlce*.v     2+^| 0.000            ^|  00   ^|  bma  ^|    eew   ^|   00001  ^| xxyyy11
                      ^| 00000    ^|  0   ^|  rs2  ^|  rs1  ^|    001   ^|     md   ^| 0111111

.2+^.^| msae*.v     2+^| 0.000            ^|  01   ^|  bma  ^|    eew   ^|   00001  ^| xxyyy11
                      ^| 00000    ^|  1   ^|  rs2  ^|  rs1  ^|    001   ^|    ms3   ^| 0111111
.2+^.^| msbe*.v     2+^| 0.000            ^|  10   ^|  bma  ^|    eew   ^|   00001  ^| xxyyy11
                      ^| 00000    ^|  1   ^|  rs2  ^|  rs1  ^|    001   ^|    ms3   ^| 0111111
.2+^.^| msce*.v     2+^| 0.000            ^|  00   ^|  bma  ^|    eew   ^|   00001  ^| xxyyy11
                      ^| 00000    ^|  1   ^|  rs2  ^|  rs1  ^|    001   ^|    ms3   ^| 0111111

.2+^.^| mlufae*.m   2+^| 0.000            ^|  01   ^|  bma  ^|    eew   ^|   00010  ^| xxyyy11
                      ^| 00000    ^|  0   ^|  rs2  ^|  rs1  ^|    001   ^|     md   ^| 0111111
.2+^.^| mlufbe*.m   2+^| 0.000            ^|  10   ^|  bma  ^|    eew   ^|   00010  ^| xxyyy11
                      ^| 00000    ^|  0   ^|  rs2  ^|  rs1  ^|    001   ^|     md   ^| 0111111
.2+^.^| mlufce*.m   2+^| 0.000            ^|  00   ^|  bma  ^|    eew   ^|   00010  ^| xxyyy11
                      ^| 00000    ^|  0   ^|  rs2  ^|  rs1  ^|    001   ^|     md   ^| 0111111

.2+^.^| msfdae*.m   2+^| 0.000            ^|  01   ^|  bma  ^|    eew   ^|   00010  ^| xxyyy11
                      ^| 00000    ^|  1   ^|  rs2  ^|  rs1  ^|    001   ^|    ms3   ^| 0111111
.2+^.^| msfdbe*.m   2+^| 0.000            ^|  10   ^|  bma  ^|    eew   ^|   00010  ^| xxyyy11
                      ^| 00000    ^|  1   ^|  rs2  ^|  rs1  ^|    001   ^|    ms3   ^| 0111111
.2+^.^| msfdce*.m   2+^| 0.000            ^|  00   ^|  bma  ^|    eew   ^|   00010  ^| xxyyy11
                      ^| 00000    ^|  1   ^|  rs2  ^|  rs1  ^|    001   ^|    ms3   ^| 0111111
|===

.Data Move Instructions
[cols="6,4,2,3,2,2,3,3,4,4"]
|===
.4+^.^| *Format*      ^| 63    59 ^|  58   ^| 57  53   ^| 52 51 ^| 50 49 ^| 48 47 ^| 46    44 ^| 43    39 ^| 38    32
                      ^|  *mks*   ^| *mk*  ^| *resv*   ^|  *rc* ^|  *mt* ^| *bma* ^|   *eew*  ^| *funct5* ^| *opcode*
                      ^| 31    26 ^|  25   ^| 24  20 3+^| 19                  15  ^| 14    12 ^| 11     7 ^| 6      0
                      ^| *funct6* ^| *di*  ^| *rs2*  3+^|        *rs1/ms1*        ^| *funct3* ^| *rd/md*  ^| *suffix*
.2+^.^| mmve*.t.t     ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   00  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   0   ^| 00000  3+^|           ms1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mmve*.a.a     ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   00  ^|  bma  ^|    eew   ^|  00001   ^| xxyyy11
                      ^|  000000  ^|   0   ^| 00000  3+^|           ms1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mmve*.a.t     ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   00  ^|  bma  ^|    eew   ^|  00010   ^| xxyyy11
                      ^|  000000  ^|   0   ^|  rs2   3+^|           ms1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mmve*.t.a     ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   00  ^|  bma  ^|    eew   ^|  00010   ^| xxyyy11
                      ^|  000000  ^|   1   ^|  rs2   3+^|           ms1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mmvie*.a.t    ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   00  ^|  bma  ^|    eew   ^|  00011   ^| xxyyy11
                      ^|  000000  ^|   0   ^|  imm   3+^|           ms1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mmvie*.t.a    ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   00  ^|  bma  ^|    eew   ^|  00011   ^| xxyyy11
                      ^|  000000  ^|   1   ^|  imm   3+^|           ms1           ^|    010   ^|    md    ^| 0111111

.2+^.^| mmve*.x.t     ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   00  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000001  ^|   0   ^|  rs2   3+^|           ms1           ^|    010   ^|    rd    ^| 0111111
.2+^.^| mmve*.t.x     ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   00  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000001  ^|   1   ^|  rs2   3+^|           rs1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mmve*.x.a     ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   00  ^|  bma  ^|    eew   ^|  00001   ^| xxyyy11
                      ^|  000001  ^|   0   ^|  rs2   3+^|           ms1           ^|    010   ^|    rd    ^| 0111111
.2+^.^| mmve*.a.x     ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   00  ^|  bma  ^|    eew   ^|  00001   ^| xxyyy11
                      ^|  000001  ^|   1   ^|  rs2   3+^|           rs1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mfmve*.x.t    ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   00  ^|  bma  ^|    eew   ^|  00010   ^| xxyyy11
                      ^|  000001  ^|   0   ^|  rs2   3+^|           ms1           ^|    010   ^|    rd    ^| 0111111
.2+^.^| mfmve*.t.x    ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   00  ^|  bma  ^|    eew   ^|  00010   ^| xxyyy11
                      ^|  000001  ^|   1   ^|  rs2   3+^|           rs1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mfmve*.x.a    ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   00  ^|  bma  ^|    eew   ^|  00011   ^| xxyyy11
                      ^|  000001  ^|   0   ^|  rs2   3+^|           ms1           ^|    010   ^|    rd    ^| 0111111
.2+^.^| mfmve*.a.x    ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   00  ^|  bma  ^|    eew   ^|  00011   ^| xxyyy11
                      ^|  000001  ^|   1   ^|  rs2   3+^|           rs1           ^|    010   ^|    md    ^| 0111111

.2+^.^| mbcar.m       ^|   mks    ^|  mk   ^| 00000    ^|   01  ^|   01  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000010  ^|   0   ^| 00000  3+^|           ms1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mbcbr.m       ^|   mks    ^|  mk   ^| 00000    ^|   01  ^|   10  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000010  ^|   0   ^| 00000  3+^|           ms1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mbccr.m       ^|   mks    ^|  mk   ^| 00000    ^|   01  ^|   00  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000010  ^|   0   ^| 00000  3+^|           ms1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mbcace*.m     ^|   mks    ^|  mk   ^| 00000    ^|   10  ^|   01  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000010  ^|   0   ^| 00000  3+^|           ms1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mbcbce*.m     ^|   mks    ^|  mk   ^| 00000    ^|   10  ^|   10  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000010  ^|   0   ^| 00000  3+^|           ms1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mbccce*.m     ^|   mks    ^|  mk   ^| 00000    ^|   10  ^|   00  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000010  ^|   0   ^| 00000  3+^|           ms1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mbcaee*.m     ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   01  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000010  ^|   0   ^| 00000  3+^|           ms1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mbcbee*.m     ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   10  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000010  ^|   0   ^| 00000  3+^|           ms1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mbccee*.m     ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   00  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000010  ^|   0   ^| 00000  3+^|           ms1           ^|    010   ^|    md    ^| 0111111

.2+^.^| mtae*.m       ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   01  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000011  ^|   0   ^| 00000  3+^|           ms1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mtbe*.m       ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   10  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000011  ^|   0   ^| 00000  3+^|           ms1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mtce*.m       ^|   mks    ^|  mk   ^| 00000    ^|   00  ^|   00  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000011  ^|   0   ^| 00000  3+^|           ms1           ^|    010   ^|    md    ^| 0111111

.2+^.^| mmvare*.v.m   ^|   mks    ^|  mk   ^| 00000    ^|   01  ^|   01  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000100  ^|   0   ^|  rs2   3+^|           ms1           ^|    010   ^|    vd    ^| 0111111
.2+^.^| mmvbre*.v.m   ^|   mks    ^|  mk   ^| 00000    ^|   01  ^|   10  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000100  ^|   0   ^|  rs2   3+^|           ms1           ^|    010   ^|    vd    ^| 0111111
.2+^.^| mmvcre*.v.m   ^|   mks    ^|  mk   ^| 00000    ^|   01  ^|   00  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000100  ^|   0   ^|  rs2   3+^|           ms1           ^|    010   ^|    vd    ^| 0111111
.2+^.^| mmvare*.m.v   ^|   mks    ^|  mk   ^| 00000    ^|   01  ^|   01  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000100  ^|   1   ^|  rs2   3+^|           vs1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mmvbre*.m.v   ^|   mks    ^|  mk   ^| 00000    ^|   01  ^|   10  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000100  ^|   1   ^|  rs2   3+^|           vs1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mmvcre*.m.v   ^|   mks    ^|  mk   ^| 00000    ^|   01  ^|   00  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000100  ^|   1   ^|  rs2   3+^|           vs1           ^|    010   ^|    md    ^| 0111111

.2+^.^| mmvace*.v.m   ^|   mks    ^|  mk   ^| 00000    ^|   10  ^|   01  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000100  ^|   0   ^|  rs2   3+^|           ms1           ^|    010   ^|    vd    ^| 0111111
.2+^.^| mmvbce*.v.m   ^|   mks    ^|  mk   ^| 00000    ^|   10  ^|   10  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000100  ^|   0   ^|  rs2   3+^|           ms1           ^|    010   ^|    vd    ^| 0111111
.2+^.^| mmvcce*.v.m   ^|   mks    ^|  mk   ^| 00000    ^|   10  ^|   00  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000100  ^|   0   ^|  rs2   3+^|           ms1           ^|    010   ^|    vd    ^| 0111111
.2+^.^| mmvace*.m.v   ^|   mks    ^|  mk   ^| 00000    ^|   10  ^|   01  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000100  ^|   1   ^|  rs2   3+^|           vs1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mmvbce*.m.v   ^|   mks    ^|  mk   ^| 00000    ^|   10  ^|   10  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000100  ^|   1   ^|  rs2   3+^|           vs1           ^|    010   ^|    md    ^| 0111111
.2+^.^| mmvcce*.m.v   ^|   mks    ^|  mk   ^| 00000    ^|   10  ^|   00  ^|  bma  ^|    eew   ^|  00000   ^| xxyyy11
                      ^|  000100  ^|   1   ^|  rs2   3+^|           vs1           ^|    010   ^|    md    ^| 0111111
|===

.Matrix Multiplication Instructions
[cols="7,4,2,3,3,3,3,4,4,5"]
|===
.4+^.^| *Format*      ^| 63    59 ^|  58    ^| 57  55 ^| 54  52 ^| 51  49 ^| 48 47 ^| 46    44 ^| 43    39 ^| 38    32
                      ^|  *sps*   ^| *sp*   ^| *typ2* ^| *typ1* ^| *typd* ^| *bma* ^|  *frm*   ^| *funct5* ^| *opcode*
                      ^| 31    26 ^|  25  2+^| 24          20 2+^| 19           15 ^| 14    12 ^| 11     7 ^| 6      0
                      ^| *funct6* ^| *fp* 2+^|       *ms2*    2+^|       *ms1*     ^| *funct3* ^|   *md*   ^| *suffix*
.2+^.^| mmau.mm       ^|  00000   ^|   0    ^|  100   ^|  100   ^|  000   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mmau.h.mm     ^|  00000   ^|   0    ^|  001   ^|  001   ^|  001   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mmau.w.mm     ^|  00000   ^|   0    ^|  010   ^|  010   ^|  010   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mmau.dw.mm    ^|  00000   ^|   0    ^|  011   ^|  011   ^|  011   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msmau.mm      ^|  00000   ^|   0    ^|  100   ^|  100   ^|  000   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msmau.h.mm    ^|  00000   ^|   0    ^|  001   ^|  001   ^|  001   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msmau.w.mm    ^|  00000   ^|   0    ^|  010   ^|  010   ^|  010   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msmau.dw.mm   ^|  00000   ^|   0    ^|  011   ^|  011   ^|  011   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mwmau.mm      ^|  00000   ^|   0    ^|  100   ^|  100   ^|  001   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mwmau.h.mm    ^|  00000   ^|   0    ^|  001   ^|  001   ^|  010   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mwmau.w.mm    ^|  00000   ^|   0    ^|  010   ^|  010   ^|  011   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mqmau.mm      ^|  00000   ^|   0    ^|  100   ^|  100   ^|  010   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mqmau.b.mm    ^|  00000   ^|   0    ^|  000   ^|  000   ^|  010   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| momau.mm      ^|  00000   ^|   0    ^|  100   ^|  100   ^|  011   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| momau.hb.mm   ^|  00000   ^|   0    ^|  111   ^|  111   ^|  011   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mswmau.mm     ^|  00000   ^|   0    ^|  100   ^|  100   ^|  001   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mswmau.h.mm   ^|  00000   ^|   0    ^|  001   ^|  001   ^|  010   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mswmau.w.mm   ^|  00000   ^|   0    ^|  010   ^|  010   ^|  011   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msqmau.mm     ^|  00000   ^|   0    ^|  100   ^|  100   ^|  010   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msqmau.b.mm   ^|  00000   ^|   0    ^|  000   ^|  000   ^|  010   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msomau.mm     ^|  00000   ^|   0    ^|  100   ^|  100   ^|  011   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msomau.hb.mm  ^|  00000   ^|   0    ^|  111   ^|  111   ^|  011   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mma.mm        ^|  00000   ^|   0    ^|  100   ^|  100   ^|  000   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mma.h.mm      ^|  00000   ^|   0    ^|  001   ^|  001   ^|  001   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mma.w.mm      ^|  00000   ^|   0    ^|  010   ^|  010   ^|  010   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mma.dw.mm     ^|  00000   ^|   0    ^|  011   ^|  011   ^|  011   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msma.mm       ^|  00000   ^|   0    ^|  100   ^|  100   ^|  000   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msma.h.mm     ^|  00000   ^|   0    ^|  001   ^|  001   ^|  001   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msma.w.mm     ^|  00000   ^|   0    ^|  010   ^|  010   ^|  010   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msma.dw.mm    ^|  00000   ^|   0    ^|  011   ^|  011   ^|  011   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mwma.mm       ^|  00000   ^|   0    ^|  100   ^|  100   ^|  001   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mwma.h.mm     ^|  00000   ^|   0    ^|  001   ^|  001   ^|  010   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mwma.w.mm     ^|  00000   ^|   0    ^|  010   ^|  010   ^|  011   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mqma.mm       ^|  00000   ^|   0    ^|  100   ^|  100   ^|  010   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mqma.b.mm     ^|  00000   ^|   0    ^|  000   ^|  000   ^|  010   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| moma.mm       ^|  00000   ^|   0    ^|  100   ^|  100   ^|  011   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| moma.hb.mm    ^|  00000   ^|   0    ^|  111   ^|  111   ^|  011   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mswma.mm      ^|  00000   ^|   0    ^|  100   ^|  100   ^|  001   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mswma.h.mm    ^|  00000   ^|   0    ^|  001   ^|  001   ^|  010   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mswma.w.mm    ^|  00000   ^|   0    ^|  010   ^|  010   ^|  011   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msqma.mm      ^|  00000   ^|   0    ^|  100   ^|  100   ^|  010   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msqma.b.mm    ^|  00000   ^|   0    ^|  000   ^|  000   ^|  010   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msoma.mm      ^|  00000   ^|   0    ^|  100   ^|  100   ^|  011   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msoma.hb.mm   ^|  00000   ^|   0    ^|  111   ^|  111   ^|  011   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mfma.mm       ^|  00000   ^|   0    ^|  100   ^|  100   ^|  000   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfma.hf.mm    ^|  00000   ^|   0    ^|  001   ^|  001   ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfma.f.mm     ^|  00000   ^|   0    ^|  010   ^|  010   ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfma.d.mm     ^|  00000   ^|   0    ^|  011   ^|  011   ^|  011   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   1  2+^|        ms2     2+^|        ms1      ^|    100   ^|    md    ^| 0111111
.2+^.^| btpmfma.f.mm  ^|  00000   ^|   0    ^|  010   ^|  010   ^|  010   ^|  bma  ^|   frm    ^|  10000   ^| xxyyy11
                      ^|  000000  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mfwma.mm      ^|  00000   ^|   0    ^|  100   ^|  100   ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfwma.cf.mm   ^|  00000   ^|   0    ^|  000   ^|  000   ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfwma.hf.mm   ^|  00000   ^|   0    ^|  001   ^|  001   ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfwma.f.mm    ^|  00000   ^|   0    ^|  010   ^|  010   ^|  011   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mfqma.mm      ^|  00000   ^|   0    ^|  100   ^|  100   ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfqma.cf.mm   ^|  00000   ^|   0    ^|  000   ^|  000   ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
|===

.Sparsing Matrix Multiplication Instructions
[cols="7,4,2,3,3,3,3,4,4,5"]
|===
.4+^.^| *Format*            ^| 63    59 ^|  58    ^| 57  55 ^| 54  52 ^| 51  49 ^| 48 47 ^| 46    44 ^| 43    39 ^| 38    32
                            ^|  *sps*   ^| *sp*   ^| *typ2* ^| *typ1* ^| *typd* ^| *bma* ^|  *frm*   ^| *funct5* ^| *opcode*
                            ^| 31    26 ^|  25  2+^| 24          20 2+^| 19           15 ^| 14    12 ^| 11     7 ^| 6      0
                            ^| *funct6* ^| *fp* 2+^|       *ms2*    2+^|       *ms1*     ^| *funct3* ^|   *md*   ^| *suffix*
.2+^.^| mmau.spa.mm         ^|   sps    ^|   1    ^|  100   ^|  100   ^|  000   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mmau.spa.h.mm       ^|   sps    ^|   1    ^|  001   ^|  001   ^|  001   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mmau.spa.w.mm       ^|   sps    ^|   1    ^|  010   ^|  010   ^|  010   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mmau.spa.dw.mm      ^|   sps    ^|   1    ^|  011   ^|  011   ^|  011   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msmau.spa.mm        ^|   sps    ^|   1    ^|  100   ^|  100   ^|  000   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msmau.spa.h.mm      ^|   sps    ^|   1    ^|  001   ^|  001   ^|  001   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msmau.spa.w.mm      ^|   sps    ^|   1    ^|  010   ^|  010   ^|  010   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msmau.spa.dw.mm     ^|   sps    ^|   1    ^|  011   ^|  011   ^|  011   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mwmau.spa.mm        ^|   sps    ^|   1    ^|  100   ^|  100   ^|  001   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mwmau.spa.h.mm      ^|   sps    ^|   1    ^|  001   ^|  001   ^|  010   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mwmau.spa.w.mm      ^|   sps    ^|   1    ^|  010   ^|  010   ^|  011   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mqmau.spa.mm        ^|   sps    ^|   1    ^|  100   ^|  100   ^|  010   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mqmau.spa.b.mm      ^|   sps    ^|   1    ^|  000   ^|  000   ^|  010   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| momau.spa.mm        ^|   sps    ^|   1    ^|  100   ^|  100   ^|  011   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| momau.spa.hb.mm     ^|   sps    ^|   1    ^|  111   ^|  111   ^|  011   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mswmau.spa.mm       ^|   sps    ^|   1    ^|  100   ^|  100   ^|  001   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mswmau.spa.h.mm     ^|   sps    ^|   1    ^|  001   ^|  001   ^|  010   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mswmau.spa.w.mm     ^|   sps    ^|   1    ^|  010   ^|  010   ^|  011   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msqmau.spa.mm       ^|   sps    ^|   1    ^|  100   ^|  100   ^|  010   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msqmau.spa.b.mm     ^|   sps    ^|   1    ^|  000   ^|  000   ^|  010   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msomau.spa.mm       ^|   sps    ^|   1    ^|  100   ^|  100   ^|  011   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msomau.spa.hb.mm    ^|   sps    ^|   1    ^|  111   ^|  111   ^|  011   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mma.spa.mm          ^|   sps    ^|   1    ^|  100   ^|  100   ^|  000   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mma.spa.h.mm        ^|   sps    ^|   1    ^|  001   ^|  001   ^|  001   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mma.spa.w.mm        ^|   sps    ^|   1    ^|  010   ^|  010   ^|  010   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mma.spa.dw.mm       ^|   sps    ^|   1    ^|  011   ^|  011   ^|  011   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msma.spa.mm         ^|   sps    ^|   1    ^|  100   ^|  100   ^|  000   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msma.spa.h.mm       ^|   sps    ^|   1    ^|  001   ^|  001   ^|  001   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msma.spa.w.mm       ^|   sps    ^|   1    ^|  010   ^|  010   ^|  010   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msma.spa.dw.mm      ^|   sps    ^|   1    ^|  011   ^|  011   ^|  011   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mwma.spa.mm         ^|   sps    ^|   1    ^|  100   ^|  100   ^|  001   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mwma.spa.h.mm       ^|   sps    ^|   1    ^|  001   ^|  001   ^|  010   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mwma.spa.w.mm       ^|   sps    ^|   1    ^|  010   ^|  010   ^|  011   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mqma.spa.mm         ^|   sps    ^|   1    ^|  100   ^|  100   ^|  010   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mqma.spa.b.mm       ^|   sps    ^|   1    ^|  000   ^|  000   ^|  010   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| moma.spa.mm         ^|   sps    ^|   1    ^|  100   ^|  100   ^|  011   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| moma.spa.hb.mm      ^|   sps    ^|   1    ^|  111   ^|  111   ^|  011   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mswma.spa.mm        ^|   sps    ^|   1    ^|  100   ^|  100   ^|  001   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mswma.spa.h.mm      ^|   sps    ^|   1    ^|  001   ^|  001   ^|  010   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mswma.spa.w.mm      ^|   sps    ^|   1    ^|  010   ^|  010   ^|  011   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msqma.spa.mm        ^|   sps    ^|   1    ^|  100   ^|  100   ^|  010   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msqma.spa.b.mm      ^|   sps    ^|   1    ^|  000   ^|  000   ^|  010   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msoma.spa.mm        ^|   sps    ^|   1    ^|  100   ^|  100   ^|  011   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msoma.spa.hb.mm     ^|   sps    ^|   1    ^|  111   ^|  111   ^|  011   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mfma.spa.mm         ^|   sps    ^|   1    ^|  100   ^|  100   ^|  000   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfma.spa.hf.mm      ^|   sps    ^|   1    ^|  001   ^|  001   ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfma.spa.f.mm       ^|   sps    ^|   1    ^|  010   ^|  010   ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfma.spa.d.mm       ^|   sps    ^|   1    ^|  011   ^|  011   ^|  011   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mfwma.spa.mm        ^|   sps    ^|   1    ^|  100   ^|  100   ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfwma.spa.cf.mm     ^|   sps    ^|   1    ^|  000   ^|  000   ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfwma.spa.hf.mm     ^|   sps    ^|   1    ^|  001   ^|  001   ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfwma.spa.f.mm      ^|   sps    ^|   1    ^|  010   ^|  010   ^|  011   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mfqma.spa.mm        ^|   sps    ^|   1    ^|  100   ^|  100   ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfqma.spa.cf.mm     ^|   sps    ^|   1    ^|  000   ^|  000   ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000001  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mmau.spb.mm         ^|   sps    ^|   1    ^|  100   ^|  100   ^|  000   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mmau.spb.h.mm       ^|   sps    ^|   1    ^|  001   ^|  001   ^|  001   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mmau.spb.w.mm       ^|   sps    ^|   1    ^|  010   ^|  010   ^|  010   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mmau.spb.dw.mm      ^|   sps    ^|   1    ^|  011   ^|  011   ^|  011   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msmau.spb.mm        ^|   sps    ^|   1    ^|  100   ^|  100   ^|  000   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msmau.spb.h.mm      ^|   sps    ^|   1    ^|  001   ^|  001   ^|  001   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msmau.spb.w.mm      ^|   sps    ^|   1    ^|  010   ^|  010   ^|  010   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msmau.spb.dw.mm     ^|   sps    ^|   1    ^|  011   ^|  011   ^|  011   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mwmau.spb.mm        ^|   sps    ^|   1    ^|  100   ^|  100   ^|  001   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mwmau.spb.h.mm      ^|   sps    ^|   1    ^|  001   ^|  001   ^|  010   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mwmau.spb.w.mm      ^|   sps    ^|   1    ^|  010   ^|  010   ^|  011   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mqmau.spb.mm        ^|   sps    ^|   1    ^|  100   ^|  100   ^|  010   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mqmau.spb.b.mm      ^|   sps    ^|   1    ^|  000   ^|  000   ^|  010   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| momau.spb.mm        ^|   sps    ^|   1    ^|  100   ^|  100   ^|  011   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| momau.spb.hb.mm     ^|   sps    ^|   1    ^|  111   ^|  111   ^|  011   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mswmau.spb.mm       ^|   sps    ^|   1    ^|  100   ^|  100   ^|  001   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mswmau.spb.h.mm     ^|   sps    ^|   1    ^|  001   ^|  001   ^|  010   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mswmau.spb.w.mm     ^|   sps    ^|   1    ^|  010   ^|  010   ^|  011   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msqmau.spb.mm       ^|   sps    ^|   1    ^|  100   ^|  100   ^|  010   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msqmau.spb.b.mm     ^|   sps    ^|   1    ^|  000   ^|  000   ^|  010   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msomau.spb.mm       ^|   sps    ^|   1    ^|  100   ^|  100   ^|  011   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msomau.spb.hb.mm    ^|   sps    ^|   1    ^|  111   ^|  111   ^|  011   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mma.spb.mm          ^|   sps    ^|   1    ^|  100   ^|  100   ^|  000   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mma.spb.h.mm        ^|   sps    ^|   1    ^|  001   ^|  001   ^|  001   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mma.spb.w.mm        ^|   sps    ^|   1    ^|  010   ^|  010   ^|  010   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mma.spb.dw.mm       ^|   sps    ^|   1    ^|  011   ^|  011   ^|  011   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msma.spb.mm         ^|   sps    ^|   1    ^|  100   ^|  100   ^|  000   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msma.spb.h.mm       ^|   sps    ^|   1    ^|  001   ^|  001   ^|  001   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msma.spb.w.mm       ^|   sps    ^|   1    ^|  010   ^|  010   ^|  010   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msma.spb.dw.mm      ^|   sps    ^|   1    ^|  011   ^|  011   ^|  011   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mwma.spb.mm         ^|   sps    ^|   1    ^|  100   ^|  100   ^|  001   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mwma.spb.h.mm       ^|   sps    ^|   1    ^|  001   ^|  001   ^|  010   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mwma.spb.w.mm       ^|   sps    ^|   1    ^|  010   ^|  010   ^|  011   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mqma.spb.mm         ^|   sps    ^|   1    ^|  100   ^|  100   ^|  010   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mqma.spb.b.mm       ^|   sps    ^|   1    ^|  000   ^|  000   ^|  010   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| moma.spb.mm         ^|   sps    ^|   1    ^|  100   ^|  100   ^|  011   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| moma.spb.hb.mm      ^|   sps    ^|   1    ^|  111   ^|  111   ^|  011   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mswma.spb.mm        ^|   sps    ^|   1    ^|  100   ^|  100   ^|  001   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mswma.spb.h.mm      ^|   sps    ^|   1    ^|  001   ^|  001   ^|  010   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mswma.spb.w.mm      ^|   sps    ^|   1    ^|  010   ^|  010   ^|  011   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msqma.spb.mm        ^|   sps    ^|   1    ^|  100   ^|  100   ^|  010   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msqma.spb.b.mm      ^|   sps    ^|   1    ^|  000   ^|  000   ^|  010   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msoma.spb.mm        ^|   sps    ^|   1    ^|  100   ^|  100   ^|  011   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| msoma.spb.hb.mm     ^|   sps    ^|   1    ^|  111   ^|  111   ^|  011   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                            ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mfma.spb.mm         ^|   sps    ^|   1    ^|  100   ^|  100   ^|  000   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfma.spb.hf.mm      ^|   sps    ^|   1    ^|  001   ^|  001   ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfma.spb.f.mm       ^|   sps    ^|   1    ^|  010   ^|  010   ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfma.spb.d.mm       ^|   sps    ^|   1    ^|  011   ^|  011   ^|  011   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mfwma.spb.mm        ^|   sps    ^|   1    ^|  100   ^|  100   ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfwma.spb.cf.mm     ^|   sps    ^|   1    ^|  000   ^|  000   ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfwma.spb.hf.mm     ^|   sps    ^|   1    ^|  001   ^|  001   ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfwma.spb.f.mm      ^|   sps    ^|   1    ^|  010   ^|  010   ^|  011   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111

.2+^.^| mfqma.spb.mm        ^|   sps    ^|   1    ^|  100   ^|  100   ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
.2+^.^| mfqma.spb.cf.mm     ^|   sps    ^|   1    ^|  000   ^|  000   ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                            ^|  000010  ^|   1  2+^|        ms2     2+^|        ms1      ^|   100    ^|    md    ^| 0111111
|===

.Element-wise Arithmetic & Logic Instructions
[cols="6,4,2,3,3,3,3,4,4,4"]
|===
.4+^.^| *Format*      ^| 63    59 ^|  58    ^| 57  55 ^| 54  52 ^| 51  49 ^| 48 47 ^| 46    44 ^| 43    39 ^| 38    32
                      ^|  *mks*   ^| *mk*   ^| *typ2* ^| *typ1* ^| *typd* ^| *bma* ^|  *frm*   ^| *funct5* ^| *opcode*
                      ^| 31    26 ^|  25  2+^| 24          20 2+^| 19           15 ^| 14    12 ^| 11     7 ^| 6      0
                      ^| *funct6* ^| *fp* 2+^|       *ms2*    2+^|       *ms1*     ^| *funct3* ^|   *md*   ^| *suffix*
.2+^.^| maddu.*.mm    ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| msaddu.*.mm   ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mwaddu.*.mm   ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|   +1   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| madd.*.mm     ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| msadd.*.mm    ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mwadd.*.mm    ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|   +1   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| msubu.*.mm    ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  00010   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mssubu.*.mm   ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  10010   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mwsubu.*.mm   ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|   +1   ^|  bma  ^|   000    ^|  00010   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| msub.*.mm     ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  00011   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mssub.*.mm    ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  10011   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mwsub.*.mm    ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|   +1   ^|  bma  ^|   000    ^|  00011   ^| xxyyy11
                      ^|  000000  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111

.2+^.^| mminu.*.mm    ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                      ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mmin.*.mm     ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                      ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mmaxu.*.mm    ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  00010   ^| xxyyy11
                      ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mmax.*.mm     ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  00011   ^| xxyyy11
                      ^|  000001  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111

.2+^.^| mand.*.mm     ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                      ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mor.*.mm      ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                      ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mxor.*.mm     ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  00010   ^| xxyyy11
                      ^|  000010  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111

.2+^.^| msll.*.mm     ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                      ^|  000011  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| msrl.*.mm     ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                      ^|  000011  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| msra.*.mm     ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  00010   ^| xxyyy11
                      ^|  000011  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111

.2+^.^| mmul.*.mm     ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                      ^|  000100  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mmulh.*.mm    ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                      ^|  000100  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mmulhu.*.mm   ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  00010   ^| xxyyy11
                      ^|  000100  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mmulhsu.*.mm  ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  00011   ^| xxyyy11
                      ^|  000100  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| msmulu.*.mm   ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  10000   ^| xxyyy11
                      ^|  000100  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| msmul.*.mm    ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  10001   ^| xxyyy11
                      ^|  000100  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| msmulsu.*.mm  ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   000    ^|  10011   ^| xxyyy11
                      ^|  000100  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mwmulu.*.mm   ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|   +1   ^|  bma  ^|   000    ^|  00000   ^| xxyyy11
                      ^|  000100  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mwmul.*.mm    ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|   +1   ^|  bma  ^|   000    ^|  00001   ^| xxyyy11
                      ^|  000100  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mwmulsu.*.mm  ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|   +1   ^|  bma  ^|   000    ^|  00011   ^| xxyyy11
                      ^|  000100  ^|   0  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111

.2+^.^| mfadd.*.mm    ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   1  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mfwadd.*.mm   ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|   +1   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                      ^|  000000  ^|   1  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mfsub.*.mm    ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                      ^|  000000  ^|   1  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mfwsub.*.mm   ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|   +1   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                      ^|  000000  ^|   1  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111

.2+^.^| mfmin.*.mm    ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                      ^|  000001  ^|   1  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mfmax.*.mm    ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   frm    ^|  00010   ^| xxyyy11
                      ^|  000001  ^|   1  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111

.2+^.^| mfmul.*.mm    ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                      ^|  000100  ^|   1  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
.2+^.^| mfwmul.*.mm   ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|   +1   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                      ^|  000100  ^|   1  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111

.2+^.^| mfdiv.*.mm    ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                      ^|  000101  ^|   1  2+^|        ms2     2+^|        ms1      ^|   101    ^|    md    ^| 0111111

.2+^.^| mfsqrt.*.mm   ^|   mks    ^|  mk    ^|  eew   ^|  eew   ^|  eew   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                      ^|  000110  ^|   1  2+^|      00000     2+^|        ms1      ^|   101    ^|    md    ^| 0111111
|===

.Type Convert Instructions
[cols="6,4,2,3,3,3,3,4,4,4"]
|===
.4+^.^| *Format*         ^| 63    59 ^|  58   ^| 57 55 ^| 54  52     ^| 51  49 ^| 48 47 ^| 46    44 ^| 43    39 ^| 38    32
                         ^|  *mks*   ^| *mk*  ^| *enw* ^| *typ1*     ^| *typd* ^| *bma* ^|  *frm*   ^| *funct5* ^| *opcode*
                         ^| 31    26 ^|  25   ^|  24   ^| 23    20 2+^| 19           15 ^| 14    12 ^| 11     7 ^| 6      0
                         ^| *funct6* ^| *fp*  ^| *fs*  ^|  *f4*    2+^|      *ms1*      ^| *funct3* ^|   *md*   ^| *suffix*
.2+^.^| mcvt.x.xu.m      ^|   mks    ^|  mk   ^|  000  ^|  100       ^|  000   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mcvt.hb.uhb.m    ^|   mks    ^|  mk   ^|  000  ^|  111       ^|  000   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mcvt.b.ub.m      ^|   mks    ^|  mk   ^|  000  ^|  000       ^|  000   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mcvt.h.uh.m      ^|   mks    ^|  mk   ^|  000  ^|  001       ^|  000   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mcvt.w.uw.m      ^|   mks    ^|  mk   ^|  000  ^|  010       ^|  000   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mcvt.dw.udw.m    ^|   mks    ^|  mk   ^|  000  ^|  011       ^|  000   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111

.2+^.^| mcvt.xu.x.m      ^|   mks    ^|  mk   ^|  000  ^|  100       ^|  000   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mcvt.uhb.hb.m    ^|   mks    ^|  mk   ^|  000  ^|  111       ^|  000   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mcvt.ub.b.m      ^|   mks    ^|  mk   ^|  000  ^|  000       ^|  000   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mcvt.uh.h.m      ^|   mks    ^|  mk   ^|  000  ^|  001       ^|  000   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mcvt.uw.w.m      ^|   mks    ^|  mk   ^|  000  ^|  010       ^|  000   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mcvt.udw.dw.m    ^|   mks    ^|  mk   ^|  000  ^|  011       ^|  000   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111

.2+^.^| mwcvtu.xw.x.m    ^|   mks    ^|  mk   ^|  001  ^|  100       ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mwcvtu.xq.x.m    ^|   mks    ^|  mk   ^|  010  ^|  100       ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mwcvtu.xo.x.m    ^|   mks    ^|  mk   ^|  011  ^|  100       ^|  011   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mwcvtu.b.hb.m    ^|   mks    ^|  mk   ^|  001  ^|  111       ^|  000   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mwcvtu.h.hb.m    ^|   mks    ^|  mk   ^|  010  ^|  111       ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mwcvtu.w.hb.m    ^|   mks    ^|  mk   ^|  011  ^|  111       ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mwcvtu.h.b.m     ^|   mks    ^|  mk   ^|  001  ^|  000       ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mwcvtu.w.b.m     ^|   mks    ^|  mk   ^|  010  ^|  000       ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mwcvtu.w.h.m     ^|   mks    ^|  mk   ^|  001  ^|  001       ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mwcvtu.dw.w.m    ^|   mks    ^|  mk   ^|  001  ^|  010       ^|  011   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111

.2+^.^| mwcvt.xw.x.m     ^|   mks    ^|  mk   ^|  001  ^|  100       ^|  001   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mwcvt.xq.x.m     ^|   mks    ^|  mk   ^|  010  ^|  100       ^|  010   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mwcvt.xo.x.m     ^|   mks    ^|  mk   ^|  011  ^|  100       ^|  011   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mwcvt.b.hb.m     ^|   mks    ^|  mk   ^|  001  ^|  111       ^|  000   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mwcvt.h.hb.m     ^|   mks    ^|  mk   ^|  010  ^|  111       ^|  001   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mwcvt.w.hb.m     ^|   mks    ^|  mk   ^|  011  ^|  111       ^|  010   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mwcvt.h.b.m      ^|   mks    ^|  mk   ^|  001  ^|  000       ^|  001   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mwcvt.w.b.m      ^|   mks    ^|  mk   ^|  010  ^|  000       ^|  010   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mwcvt.w.h.m      ^|   mks    ^|  mk   ^|  001  ^|  001       ^|  010   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mwcvt.dw.w.m     ^|   mks    ^|  mk   ^|  001  ^|  010       ^|  011   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111

.2+^.^| mncvtu.x.xw.m    ^|   mks    ^|  mk   ^|  111  ^|  100       ^|  111   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mncvtu.x.xq.m    ^|   mks    ^|  mk   ^|  110  ^|  100       ^|  110   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mncvtu.x.xo.m    ^|   mks    ^|  mk   ^|  101  ^|  100       ^|  101   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mncvtu.hb.b.m    ^|   mks    ^|  mk   ^|  111  ^|  000       ^|  111   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mncvtu.hb.h.m    ^|   mks    ^|  mk   ^|  110  ^|  001       ^|  111   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mncvtu.hb.w.m    ^|   mks    ^|  mk   ^|  101  ^|  010       ^|  111   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mncvtu.b.h.m     ^|   mks    ^|  mk   ^|  111  ^|  001       ^|  000   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mncvtu.b.w.m     ^|   mks    ^|  mk   ^|  110  ^|  010       ^|  000   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mncvtu.h.w.m     ^|   mks    ^|  mk   ^|  111  ^|  010       ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mncvtu.w.dw.m    ^|   mks    ^|  mk   ^|  111  ^|  011       ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111

.2+^.^| mncvt.x.xw.m     ^|   mks    ^|  mk   ^|  111  ^|  100       ^|  111   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mncvt.x.xq.m     ^|   mks    ^|  mk   ^|  110  ^|  100       ^|  110   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mncvt.x.xo.m     ^|   mks    ^|  mk   ^|  101  ^|  100       ^|  101   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mncvt.hb.b.m     ^|   mks    ^|  mk   ^|  111  ^|  000       ^|  111   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mncvt.hb.h.m     ^|   mks    ^|  mk   ^|  110  ^|  001       ^|  111   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mncvt.hb.w.m     ^|   mks    ^|  mk   ^|  101  ^|  010       ^|  111   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mncvt.b.h.m      ^|   mks    ^|  mk   ^|  111  ^|  001       ^|  000   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mncvt.b.w.m      ^|   mks    ^|  mk   ^|  110  ^|  010       ^|  000   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mncvt.h.w.m      ^|   mks    ^|  mk   ^|  111  ^|  010       ^|  001   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mncvt.w.dw.m     ^|   mks    ^|  mk   ^|  111  ^|  011       ^|  010   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111

.2+^.^| mfcvt.bf.hf.m    ^|   mks    ^|  mk   ^|  000  ^|  001       ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfcvt.hf.bf.m    ^|   mks    ^|  mk   ^|  000  ^|  001       ^|  001   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvt.fw.f.m    ^|   mks    ^|  mk   ^|  001  ^|  100       ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvt.hf.cf.m   ^|   mks    ^|  mk   ^|  001  ^|  000       ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvt.f.hf.m    ^|   mks    ^|  mk   ^|  001  ^|  001       ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvt.d.f.m     ^|   mks    ^|  mk   ^|  001  ^|  010       ^|  011   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvt.f.fw.m    ^|   mks    ^|  mk   ^|  111  ^|  100       ^|  111   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvt.cf.hf.m   ^|   mks    ^|  mk   ^|  111  ^|  001       ^|  000   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvt.hf.f.m    ^|   mks    ^|  mk   ^|  111  ^|  010       ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvt.f.d.m     ^|   mks    ^|  mk   ^|  111  ^|  011       ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111

.2+^.^| mfcvtu.f.x.m     ^|   mks    ^|  mk   ^|  000  ^|  100       ^|  000   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfcvtu.hf.h.m    ^|   mks    ^|  mk   ^|  000  ^|  001       ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfcvtu.f.w.m     ^|   mks    ^|  mk   ^|  000  ^|  010       ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfcvtu.d.dw.m    ^|   mks    ^|  mk   ^|  000  ^|  011       ^|  011   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfcvt.f.x.m      ^|   mks    ^|  mk   ^|  000  ^|  100       ^|  000   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfcvt.hf.h.m     ^|   mks    ^|  mk   ^|  000  ^|  001       ^|  001   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfcvt.f.w.m      ^|   mks    ^|  mk   ^|  000  ^|  010       ^|  010   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfcvt.d.dw.m     ^|   mks    ^|  mk   ^|  000  ^|  011       ^|  011   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111

.2+^.^| mfwcvtu.fw.x.m   ^|   mks    ^|  mk   ^|  001  ^|  100       ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvtu.fq.x.m   ^|   mks    ^|  mk   ^|  010  ^|  100       ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvtu.fo.x.m   ^|   mks    ^|  mk   ^|  011  ^|  100       ^|  011   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvtu.hf.hb.m  ^|   mks    ^|  mk   ^|  010  ^|  111       ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvtu.f.hb.m   ^|   mks    ^|  mk   ^|  011  ^|  111       ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvtu.hf.b.m   ^|   mks    ^|  mk   ^|  001  ^|  000       ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvtu.f.b.m    ^|   mks    ^|  mk   ^|  010  ^|  000       ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvtu.f.h.m    ^|   mks    ^|  mk   ^|  001  ^|  001       ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvtu.d.w.m    ^|   mks    ^|  mk   ^|  001  ^|  010       ^|  011   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvt.fw.x.m    ^|   mks    ^|  mk   ^|  001  ^|  100       ^|  001   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvt.fq.x.m    ^|   mks    ^|  mk   ^|  010  ^|  100       ^|  010   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvt.fo.x.m    ^|   mks    ^|  mk   ^|  011  ^|  100       ^|  011   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvt.hf.hb.m   ^|   mks    ^|  mk   ^|  010  ^|  111       ^|  001   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvt.f.hb.m    ^|   mks    ^|  mk   ^|  011  ^|  111       ^|  010   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvt.hf.b.m    ^|   mks    ^|  mk   ^|  001  ^|  000       ^|  001   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvt.f.b.m     ^|   mks    ^|  mk   ^|  010  ^|  000       ^|  010   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvt.f.h.m     ^|   mks    ^|  mk   ^|  001  ^|  001       ^|  010   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvt.d.w.m     ^|   mks    ^|  mk   ^|  001  ^|  010       ^|  011   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111

.2+^.^| mfncvtu.f.xw.m   ^|   mks    ^|  mk   ^|  111  ^|  100       ^|  111   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvtu.hf.w.m   ^|   mks    ^|  mk   ^|  111  ^|  010       ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvtu.f.dw.m   ^|   mks    ^|  mk   ^|  111  ^|  011       ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvt.f.xw.m    ^|   mks    ^|  mk   ^|  111  ^|  100       ^|  111   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvt.hf.w.m    ^|   mks    ^|  mk   ^|  111  ^|  010       ^|  001   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvt.f.dw.m    ^|   mks    ^|  mk   ^|  111  ^|  011       ^|  010   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   1   ^|   0   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111

.2+^.^| mfcvtu.x.f.m     ^|   mks    ^|  mk   ^|  000  ^|  100       ^|  000   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfcvtu.h.hf.m    ^|   mks    ^|  mk   ^|  000  ^|  001       ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfcvtu.w.f.m     ^|   mks    ^|  mk   ^|  000  ^|  010       ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfcvtu.dw.d.m    ^|   mks    ^|  mk   ^|  000  ^|  011       ^|  011   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfcvt.x.f.m      ^|   mks    ^|  mk   ^|  000  ^|  100       ^|  000   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfcvt.h.hf.m     ^|   mks    ^|  mk   ^|  000  ^|  001       ^|  001   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfcvt.w.f.m      ^|   mks    ^|  mk   ^|  000  ^|  010       ^|  010   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfcvt.dw.d.m     ^|   mks    ^|  mk   ^|  000  ^|  011       ^|  011   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111

.2+^.^| mfwcvtu.xw.f.m   ^|   mks    ^|  mk   ^|  001  ^|  100       ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvtu.w.hf.m   ^|   mks    ^|  mk   ^|  001  ^|  001       ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvtu.dw.f.m   ^|   mks    ^|  mk   ^|  001  ^|  010       ^|  011   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvt.xw.f.m    ^|   mks    ^|  mk   ^|  001  ^|  100       ^|  001   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvt.w.hf.m    ^|   mks    ^|  mk   ^|  001  ^|  001       ^|  010   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfwcvt.dw.f.m    ^|   mks    ^|  mk   ^|  001  ^|  010       ^|  011   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111

.2+^.^| mfncvtu.x.fw.m   ^|   mks    ^|  mk   ^|  111  ^|  100       ^|  111   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvtu.x.fq.m   ^|   mks    ^|  mk   ^|  110  ^|  100       ^|  110   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvtu.x.fo.m   ^|   mks    ^|  mk   ^|  101  ^|  100       ^|  101   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvtu.hb.hf.m  ^|   mks    ^|  mk   ^|  110  ^|  001       ^|  111   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvtu.hb.f.m   ^|   mks    ^|  mk   ^|  101  ^|  010       ^|  111   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvtu.b.hf.m   ^|   mks    ^|  mk   ^|  111  ^|  001       ^|  000   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvtu.b.f.m    ^|   mks    ^|  mk   ^|  110  ^|  010       ^|  000   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvtu.h.f.m    ^|   mks    ^|  mk   ^|  111  ^|  010       ^|  001   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvtu.w.d.m    ^|   mks    ^|  mk   ^|  111  ^|  011       ^|  010   ^|  bma  ^|   frm    ^|  00000   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvt.x.fw.m    ^|   mks    ^|  mk   ^|  111  ^|  100       ^|  111   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvt.x.fq.m    ^|   mks    ^|  mk   ^|  110  ^|  100       ^|  110   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvt.x.fo.m    ^|   mks    ^|  mk   ^|  101  ^|  100       ^|  101   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvt.hb.hf.m   ^|   mks    ^|  mk   ^|  110  ^|  001       ^|  111   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvt.hb.f.m    ^|   mks    ^|  mk   ^|  101  ^|  010       ^|  111   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvt.b.hf.m    ^|   mks    ^|  mk   ^|  111  ^|  001       ^|  000   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvt.b.f.m     ^|   mks    ^|  mk   ^|  110  ^|  010       ^|  000   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvt.h.f.m     ^|   mks    ^|  mk   ^|  111  ^|  010       ^|  001   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
.2+^.^| mfncvt.w.d.m     ^|   mks    ^|  mk   ^|  111  ^|  011       ^|  010   ^|  bma  ^|   frm    ^|  00001   ^| xxyyy11
                         ^|  000000  ^|   0   ^|   1   ^|  0000    2+^|       ms1       ^|   111    ^|    md    ^| 0111111
|===
